#!/usr/bin/env python3
"""
/write · Shipwright seomachine-cn
输入: research brief markdown 路径
输出: src/content/blog/<slug>.mdx · 符合 Astro Content Schema

Phase 1.5: 基于 brief + 模板生成结构 · 内容填占位符
Phase 2: 调 Claude Sonnet API 生成真实内容
"""

from __future__ import annotations
import argparse
import datetime as dt
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BLOG_DIR = ROOT / "src" / "content" / "blog"


def parse_brief(brief_path: Path) -> dict:
    content = brief_path.read_text(encoding="utf-8")
    data = {"seedKeyword": "", "cluster": "supporting", "intent": "top"}

    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            fm = parts[1]
            for line in fm.strip().split("\n"):
                if ":" in line:
                    k, v = line.split(":", 1)
                    data[k.strip()] = v.strip().strip('"')

    # Extract top 5 keywords from H2 1
    kws: list[str] = []
    m = re.search(r"\| 1 \| (.+?) \|", content)
    if m:
        kws.append(m.group(1).strip())
    for match in re.finditer(r"\| \d+ \| (.+?) \|", content):
        kw = match.group(1).strip()
        if kw not in kws and len(kws) < 8:
            kws.append(kw)

    # Extract PAA
    paa_m = re.search(r"## 3\. People Also Ask\s*\n\s*\n((?:- .+\n)+)", content)
    paa = []
    if paa_m:
        paa = [line[2:].strip() for line in paa_m.group(1).strip().split("\n")]

    data["keywords"] = kws[:8]
    data["paa"] = paa
    data["suggestedCluster"] = data.get("suggestedCluster", data.get("cluster", "supporting"))
    return data


def slugify(text: str) -> str:
    text = text.strip().lower()
    text = re.sub(r"\s+", "-", text)
    text = re.sub(r"[^\w一-鿿\-]", "", text)
    return text[:80]


def build_mdx(meta: dict) -> str:
    seed = meta["seedKeyword"]
    cluster = meta["suggestedCluster"]
    kws = meta["keywords"]
    paa = meta["paa"]
    is_pillar = cluster.startswith("pillar")
    target_len = "3500-5500" if is_pillar else "2500-3500"
    today = dt.date.today().isoformat()

    title = f"{seed} · 完整实战指南" if is_pillar else f"{seed} · 实战方法论"
    description = f"{seed} 的 Shipwright 实战指南 · 拆解方法论 + 路径对比 + 真实 before/after KPI + 决策矩阵. 基于 14 天交付跨境电商 DTC 的 {len(kws)} 条 supporting 关键词.".replace("\n", "")
    description = description[:155]

    lines: list[str] = []
    lines.append("---")
    lines.append(f'title: "{title}"')
    lines.append(f'description: "{description}"')
    lines.append(f"pubDate: {today}")
    lines.append(f"locale: zh-CN")
    lines.append(f"cluster: {cluster}")
    lines.append(f"keywords:")
    for kw in kws[:8]:
        lines.append(f'  - "{kw}"')
    lines.append('author: "Shipwright Team"')
    lines.append("status: draft   # 提醒 · /optimize-baidu 后 review 再改 published")
    lines.append("---")
    lines.append("")
    lines.append("## TL;DR")
    lines.append("")
    lines.append(f"_{seed}_ 的实战: 3 件工程事实 + 2 个 before/after 真数字. {target_len} 字 · Shipwright 14 天方法论实战产出.")
    lines.append("")
    lines.append("- [ ] **填充 takeaway 1** · 一句话结论")
    lines.append("- [ ] **填充 takeaway 2** · 一个 KPI 数字")
    lines.append("- [ ] **填充 takeaway 3** · 一个 CTA 跳转")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## 1. 问题画像")
    lines.append("")
    lines.append(f"**典型客户画像** · 月 GMV ¥500K-$300K · Shopify/Amazon/TikTok Shop 2+ 渠道.")
    lines.append("")
    lines.append("_(TODO: 填你的场景 + 数字 · 可引用 /work/ 案例数据)_")
    lines.append("")

    lines.append(f"## 2. {seed} 的 3 个实战角度")
    lines.append("")
    lines.append("### 2.1 方法论")
    lines.append("_(TODO: 拆解解法 · 3-5 步 · 每步带可验收产物)_")
    lines.append("")
    lines.append("### 2.2 技术栈 / 工具对比")
    lines.append("| 方案 | 成本 | 时间 | 代码所有权 |")
    lines.append("|---|---|---|---|")
    lines.append("| AI Agent (Shipwright) | ¥58K | 14 天 | 100% |")
    lines.append("| 传统外包 | ¥150K+ | 4-8 周 | △ |")
    lines.append("| 通用 SaaS | 月费 | 即刻 | ✗ |")
    lines.append("")
    lines.append("### 2.3 实测 KPI")
    lines.append("_(TODO: 引用真案例 /work/ · before/after · 3 个量化指标)_")
    lines.append("")

    lines.append("## 3. 常见问题 (FAQ · 从 PAA 扩展)")
    lines.append("")
    for q in paa[:5]:
        lines.append(f"### {q}")
        lines.append(f"_(TODO: 2-3 段实战回答 · 引用具体数字 + 内链 /work 或 /scenes)_")
        lines.append("")

    lines.append("## 4. 下一步")
    lines.append("")
    lines.append(f"- 看 [14 天方法论 pillar](/blog/ai-driven-dtc-14-day-mvp)")
    lines.append(f"- 看 [相关 SKU 详情](/pricing)")
    lines.append(f"- [预约 30 分钟诊断](/contact) · 告诉你 {seed} 这个场景用哪个 SKU 最值得先做")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"**Draft generated by `seomachine-cn/src/write.py` from research brief · 人工 review 必做**.")
    lines.append("")
    lines.append("下一步:")
    lines.append("")
    lines.append("```bash")
    lines.append(f"python seomachine-cn/src/optimize_baidu.py src/content/blog/{slugify(seed)}.mdx")
    lines.append("```")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="seomachine-cn · /write")
    parser.add_argument("brief_path", help="Path to research brief markdown (e.g. docs/seo/research-xxx.md)")
    parser.add_argument("--type", default="auto", choices=["auto", "pillar", "supporting"])
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    brief_path = Path(args.brief_path)
    if not brief_path.exists():
        brief_path = ROOT / args.brief_path
    if not brief_path.exists():
        print(f"✗ Brief not found: {args.brief_path}", file=sys.stderr)
        return 1

    meta = parse_brief(brief_path)
    if not meta.get("seedKeyword"):
        print("✗ Brief missing seedKeyword in frontmatter", file=sys.stderr)
        return 1

    mdx = build_mdx(meta)
    slug = slugify(meta["seedKeyword"])

    if args.dry_run:
        print(mdx)
        return 0

    BLOG_DIR.mkdir(parents=True, exist_ok=True)
    out_path = BLOG_DIR / f"{slug}.mdx"
    if out_path.exists():
        print(f"⚠ File exists · 跳过: {out_path.relative_to(ROOT)}")
        print(f"  (手动删后重跑 or 使用 --force 功能 phase 2 添加)")
        return 0

    out_path.write_text(mdx, encoding="utf-8")
    print(f"✓ MDX draft saved: {out_path.relative_to(ROOT)}")
    print(f"  Next: python seomachine-cn/src/optimize_baidu.py {out_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
